version: "3"

services:

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: plutus
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db

  # For django web app
  web:
    build: .
    command: ["./wait-for.sh", "db:3306", "--", "python", "plutus/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/plutus
    ports:
      - "8000:8000"
    depends_on:
      - db 
