version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5678
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: plutus
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: 1234
      PMA_HOST: mariadb
